site_name: BigWham
site_url: https://bigwham.com
docs_dir: docs

nav:
  - Home: index.md
  - About: about.md
  - API: api.md
  - Installation:
    - Ubuntu: installation/ubuntu.md
  - Examples:
    - 2D Griffith Crack: examples/griffith_crack.md
  - Readme (master branch):
    - Readme v1: oldies/readmev1.md
    - Readme v2: oldies/readmev2.md